[package]
name = "hermit-entry"
version = "0.4.0"
authors = ["Martin Kröning <mkroening@posteo.net>"]
edition = "2021"
description = "RustyHermit's entry API."
repository = "https://github.com/hermitcore/hermit-entry"
license = "MIT OR Apache-2.0"
keywords = ["hermit", "unikernel"]
categories = ["api-bindings", "no-std", "virtualization"]

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-none"
targets = [
    "x86_64-unknown-none",
    "aarch64-unknown-none-softfloat",
]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
memoffset = { version = "0.6", features = ["unstable_const"], optional = true }

[features]
default = []
loader = []
kernel = ["memoffset"]
